brew "gh"
brew "git"
brew "node"
brew "nvm"
brew "ollama", restart_service: :changed
brew "poppler"
brew "zsh"
cask "cursor"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
cask "visual-studio-code"
